### ISSUE TITLE
Transport::runTicks is no longer called

### ISSUE THREAD

**Issue by marcusspangenberg** [finos/SymphonyMediaBridge#187]
In PR #172 EngineMixer::runTransportTicks was removed. This means Transport::runTick() is never called anywhere anymore. 

Was this the intent of the change, otherwise it seems like a possible issue. If runTick() is never to be used anymore, the function in Transport should be removed. Right now it just looks wrong.

**Comment by marcusspangenberg** [comment]
Ok, seems like EngineMixer::runTransportTicks was never called anywhere either. So should Transport::runTick be called ever or removed?

**Comment by reddvl1980** [comment]
I think it needs to be removed. @olofkallander, remember I showed it to you, what do you think?

**Comment by reddvl1980** [comment]
https://github.com/finos/SymphonyMediaBridge/pull/190
