### ISSUE TITLE
Director undefined behaviour

### ISSUE THREAD

**Issue by marcusspangenberg** [finos/SymphonyMediaBridge#189]
Issues after #123 was merged. Was there a profiling run done before and after this? Otherwise I don't see the purpose of introducing these changes just for the sake of optimizing.

Without digging deeper I can see some issues:

## 1
We have some situations where there is no video forwarded to a participant. I can see in the log that the value of desiredHighestEstimatedPinnedLevel is out of bounds:

2022-09-22 07:53:05.964 INFO [0x7f5c2246f700][StreamDirector-9] setUplinkEstimateKbps 1269, endpointIdHash 628728810038321742 desiredLevel 12 > level 2, scale up

12 is not a valid level value.

## 2

Undefined behaviour in the code

```
size_t pinnedQuality, unpinnedQuality;
getVideoQualityLimits(participantStream, pinnedQuality, unpinnedQuality);
```

```
inline void getVideoQualityLimits(const ParticipantStreams& participantStreams,
        size_t& outPinnedQuality,
        size_t& outUnpinnedQuality) const
    {
        const auto maxVideoStreams = std::min(std::max(1ul, _lowQualitySsrcs.size()), (unsigned long)_lastN - 1);
        if (maxVideoStreams < 1)
        {
            return;
        }
```

If maxVideoStreams is < 1 the function returns and the code above continues with the values of pinnedQuality and unpinnedQuality unset.

**Comment by marcusspangenberg** [comment]
Is the line

```
const auto maxVideoStreams = std::min(std::max(1ul, _lowQualitySsrcs.size()), (unsigned long)_lastN - 1);
```

instead supposed to be 

```
const auto maxVideoStreams = std::min(std::max(1ul, _lowQualitySsrcs.size()), (unsigned long)_lastN);

```

?

1 is a valid value of lastN (only forward one stream)

**Comment by olofkallander** [comment]
noted

**Comment by olofkallander** [comment]
bug report created

**Comment by reddvl1980** [comment]
https://github.com/finos/SymphonyMediaBridge/issues/189
