### ISSUE TITLE
Segfault when ice.singlePort set to 0 in config

### ISSUE THREAD

**Issue by marcusspangenberg** [finos/SymphonyMediaBridge#193]
### Steps to Reproduce:
Set ice.singlePort to 0 in config.json
Start application

### Expected Result:
Starting without single UDP port, using the port range instead.

### Actual Result:
Segfault in:

std::vector::begin() vector:1408
transport::TransportFactoryImpl::registerIceListener(transport::Endpoint::IEvents &, const std::string &) TransportFactory.cpp:515
bridge::Bridge::initialize(std::shared_ptr<…>) Bridge.cpp:173
bridge::Bridge::initialize() Bridge.cpp:103
main main.cpp:151
__libc_start_call_main 0x00007f11e4e58d90
__libc_start_main_impl 0x00007f11e4e58e40
_start 0x0000563af1e66955

### Environment:
Ubuntu Linux x64

**Comment by marcusspangenberg** [comment]
Introduced in #131? @stepanaksenov

**Comment by stepanaksenov** [comment]
> Introduced in #131? @stepanaksenov

Yes.

> Starting without single UDP port, using the port range instead.

But what port range should be used in this case? If ice.singlePort is 0, we don't expose any UDP endpoints:
https://github.com/finos/SymphonyMediaBridge/blob/master/transport/TransportFactory.cpp#L76

**Comment by marcusspangenberg** [comment]
Not sure what you discussed on how this should work in the future. @olofkallander has more info, but from what I remember setting iceSinglePort to 0 resulted in a random port from the udpPortRangeLow - udpPortRangeHigh range when allocating an endpoint. At least that is how we have been using it until now.

**Comment by stepanaksenov** [comment]
I've added a quick fix to avoid segfault #194 . Probing feature is not used yet, we can discuss how it should work when no shared UDP endpoints are created.
