### ISSUE TITLE
Suggestion: Move PR build pipelines to GitHub actions for visibility

### ISSUE THREAD

**Issue by marcusspangenberg** [finos/SymphonyMediaBridge#376]
### Description of Problem:
Currently the status and result of the PR build pipelines are opaque to the community contributors since they run in a closed environment.

### Potential Solutions:
Suggestion to move the PR build pipelines to GitHub actions making the results visible for all.

**Comment by RicardoMDomingues** [comment]
Yes, I thought about that too. I need to deploy docker images to a public repo first. I have that on my to do list.

**Comment by RicardoMDomingues** [comment]
@marcusspangenberg, @olofkallander, I finally moved PR checks to gitactions. PR was already merged #381
