### ISSUE TITLE
TcpEndpoint-SendJob-run, How do I ensure the sequence of SENDING TCP packets

### ISSUE THREAD

**Issue by chris-shenzhen-china** [finos/SymphonyMediaBridge#45]
there are three tcp packets to  be sent, 
1. app call TcpEndpoint->sendTo three times for packet1 , packet2, packet3;
2. TcpEndpoint---_sendJobs.addJob<SendJob>(*this, packet, target, allocator) called three times;
3. if app run 8 workThread for jobManager, How do I ensure the sequence of SENDING TCP packets for each tcp connection, packet1, packet2, packet3， may not be packet2, packet3, packet1?

**Comment by olofkallander** [comment]
JobQueue is a serializing context for jobs. If you want to process jobs in parallell, you post them directly on JobManager queue. If you want to serialize them, you post them on JobQueue, which then post them one at a time to JobManager.
