### ISSUE TITLE
Api format request/response mismatch - payload parameters

### ISSUE THREAD

**Issue by marcusspangenberg** [finos/SymphonyMediaBridge#87]
In the API, the format for the parameters object was changed from 

"parameters": [
    {"name": "minptime", "value "10"}
],

to

"parameters": {
    "minptime": "10"
},

in the requests, but the responses still use the old format.

The reasoning behind the name/value format was to be able to define JSON objects in JS/Java for parameters instead of having to reflect the key/value pairs. It would be good if it at least it was the one or the other. The examples/simpleserver code would need updating as well if the new format is to be used.

**Comment by olofkallander** [comment]
I will update the response and the sample. 
I did not see it being used much in the code and we were trying to resolve an integration issue with new client.
